[build]
  command = "npm run build"
  publish = ".vitepress/dist"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Enable Netlify Identity
[build.environment]
  NODE_VERSION = "18"
  BASE_URL = "/"

